---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - docker ps
  - ls
  
# server:
#   host:
#     from_secret: host
#   user:
#     from_secret: username
#   ssh_key:
#     from_secret: ssh_key
  
# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: super-peer
#   image: node
#   commands:
#   - node --version
#   - docker ps

# trigger:
#   branch:
#   - master
